### ISSUE TITLE
maj les trad après le changement de chan entre play voice vers voice

### ISSUE THREAD

**Issue by KimiNako** [TeamConfiture/SuNoFes#233]

**Comment by KimiNako** [comment]
"play voice" ne marche pas, il faut le remplacer par "voice"
Après ce changement, les voix sont bien mappées sur le chan "voice" dans les paramètres. Problème : cela a généré des nouvelles lignes de trad

**Comment by Ayowel** [comment]
C'est pour pouvoir gérer la langue de la voix -> normal du point de vue de Ren'Py.
Pour contourner, il faudrait déclarer un nouveau channel dans Ren'Py qu'on utiliserait pour les voix :/
