### ISSUE TITLE
Dev - Implem character labels 

### ISSUE THREAD

**Issue by Lushion** [TeamConfiture/SuNoFes#68]
Définir le nom des personnages dans "characters.py" avec leurs noms et leurs couleurs.

**Comment by Lushion** [comment]
Implémentation de X, Blanche, Madame Arc-En-Ciel, Grosso, Maigrichon, Noir, Violet et Indigo.

Est-ce que les perso ont des couleurs différentes chacun ?

**Comment by KimiNako** [comment]
> Implémentation de X, Blanche, Madame Arc-En-Ciel, Grosso, Maigrichon, Noir, Violet et Indigo.
> 
> Est-ce que les perso ont des couleurs différentes chacun ?

Oui
