### ISSUE TITLE
Bug : Empty history

### ISSUE THREAD

**Issue by KimiNako** [TeamConfiture/SuNoFes#99]
![image](https://user-images.githubusercontent.com/32203512/185174894-3881a28d-f836-42e5-a1f8-1bc443914c31.png)

**Comment by Ayowel** [comment]
A noter aussi que le premier texte du récit n'apparaît pas dans l'historique
![Peek 2022-08-17 17-50](https://user-images.githubusercontent.com/8655467/185185151-eb4b8570-5271-4018-b0ab-1775f25c4c37.gif)
